set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(DEBARCH arm64)
set(CMAKE_SYSTEM_VERSION 26) # Android API level
set(CMAKE_ANDROID_ARCH_ABI arm64-v8a)
set(CMAKE_ANDROID_NDK /YOUR/ANDROID/NDK/)
set(ZENOHC_CUSTOM_TARGET aarch64-linux-android)
